export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT';
export const SET_INGREDIENT='SET_INGREDIENT';
export const FETCH_INGREDIENTS_FAILED='FETCH_INGREDIENTS_FAILED';

export const BURGER_ORDER_SUCCESS='BURGER_ORDER_SUCCESS';
export const BURGER_ORDER_FAIL='BURGER_ORDER_FAIL';
export const BURGER_ORDER_START='BURGER_ORDER_START';
export const PURCHASE_INIT='PURCHASE_INIT';

export const FETCH_ORDER_SUCCESS='FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL='FETCH_ORDER_FAIL';
export const FETCH_ORDER_START='FETCH_ORDER_START';

export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';

export const AUTH_REDIRECTPATH='AUTH_REDIRECTPATH';